//
//  openLibreReaderTests.m
//  openLibreReaderTests
//
//  Created by Gerriet Reents on 20.01.18.
//  Copyright © 2018 Sandra Keßler. All rights reserved.
//

#import <XCTest/XCTest.h>
#import "SimpleLinearRegressionCalibration.h"
#import "calibrationValue.h"

@interface openLibreReaderTests : XCTestCase

@end

@interface SimpleLinearRegressionCalibration (Tests)
- (void)linearRegressionInternal:(double*)slope intercept:(double*)intercept xvalues:(NSArray *)xvalues yvalues:(NSArray *)yvalues ;
@end

@implementation openLibreReaderTests

- (void)setUp {
    [super setUp];
    // Put setup code here. This method is called before the invocation of each test method in the class.
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testSimpleLinearRegressionCalibration1 {
    SimpleLinearRegressionCalibration* test_instance = [[SimpleLinearRegressionCalibration alloc] init];
    double slope;
    double intercept;
    NSMutableArray* xvalues = [NSMutableArray arrayWithObjects:@1,@2,@3,nil];
    NSMutableArray* yvalues = [NSMutableArray arrayWithObjects:@1,@2,@3,nil];

    [test_instance linearRegressionInternal:&slope intercept:&intercept xvalues:xvalues yvalues:yvalues];
    XCTAssert(1 == slope);
    XCTAssert(0 == intercept);
}

- (void)testSimpleLinearRegressionCalibration2 {
    // data from https://onlinecourses.science.psu.edu/stat462/node/101 (Example 1)
    SimpleLinearRegressionCalibration* test_instance = [[SimpleLinearRegressionCalibration alloc] init];
    double slope;
    double intercept;
    NSMutableArray* xvalues = [NSMutableArray array];
    NSMutableArray* yvalues = [NSMutableArray array];
    
    [yvalues addObject:[NSNumber numberWithDouble:31.5]];            [xvalues addObject:[NSNumber numberWithDouble:20.1]];
    [yvalues addObject:[NSNumber numberWithDouble:18.9]];            [xvalues addObject:[NSNumber numberWithDouble:7.1 ]];
    [yvalues addObject:[NSNumber numberWithDouble:35.0]];            [xvalues addObject:[NSNumber numberWithDouble:16.1]];
    [yvalues addObject:[NSNumber numberWithDouble:31.6]];            [xvalues addObject:[NSNumber numberWithDouble:14.9]];
    [yvalues addObject:[NSNumber numberWithDouble:22.6]];            [xvalues addObject:[NSNumber numberWithDouble:16.7]];
    [yvalues addObject:[NSNumber numberWithDouble:26.2]];            [xvalues addObject:[NSNumber numberWithDouble:8.8 ]];
    [yvalues addObject:[NSNumber numberWithDouble:14.1]];            [xvalues addObject:[NSNumber numberWithDouble:9.7 ]];
    [yvalues addObject:[NSNumber numberWithDouble:24.7]];            [xvalues addObject:[NSNumber numberWithDouble:10.3]];
    [yvalues addObject:[NSNumber numberWithDouble:44.8]];            [xvalues addObject:[NSNumber numberWithDouble:22.0 ]];
    [yvalues addObject:[NSNumber numberWithDouble:23.2]];            [xvalues addObject:[NSNumber numberWithDouble:16.2]];
    [yvalues addObject:[NSNumber numberWithDouble:31.4]];            [xvalues addObject:[NSNumber numberWithDouble:12.1]];
    [yvalues addObject:[NSNumber numberWithDouble:17.7]];            [xvalues addObject:[NSNumber numberWithDouble:10.3]];
    [yvalues addObject:[NSNumber numberWithDouble:18.4]];            [xvalues addObject:[NSNumber numberWithDouble:14.5]];
    [yvalues addObject:[NSNumber numberWithDouble:23.4]];            [xvalues addObject:[NSNumber numberWithDouble:12.4]];
    [yvalues addObject:[NSNumber numberWithDouble:22.6]];            [xvalues addObject:[NSNumber numberWithDouble:9.6]];
    [yvalues addObject:[NSNumber numberWithDouble:16.4]];            [xvalues addObject:[NSNumber numberWithDouble:12.2]];
    [yvalues addObject:[NSNumber numberWithDouble:21.4]];            [xvalues addObject:[NSNumber numberWithDouble:10.8]];
    [yvalues addObject:[NSNumber numberWithDouble:26.5]];            [xvalues addObject:[NSNumber numberWithDouble:14.7]];
    [yvalues addObject:[NSNumber numberWithDouble:31.7]];            [xvalues addObject:[NSNumber numberWithDouble:19.7]];
    [yvalues addObject:[NSNumber numberWithDouble:11.9]];            [xvalues addObject:[NSNumber numberWithDouble:11.2]];
    [yvalues addObject:[NSNumber numberWithDouble:20.0]];            [xvalues addObject:[NSNumber numberWithDouble:10.1]];
    [yvalues addObject:[NSNumber numberWithDouble:12.5]];            [xvalues addObject:[NSNumber numberWithDouble:11.0 ]];
    [yvalues addObject:[NSNumber numberWithDouble:18.0]];            [xvalues addObject:[NSNumber numberWithDouble:12.2]];
    [yvalues addObject:[NSNumber numberWithDouble:14.2]];            [xvalues addObject:[NSNumber numberWithDouble:9.2]];
    [yvalues addObject:[NSNumber numberWithDouble:37.6]];            [xvalues addObject:[NSNumber numberWithDouble:23.5]];
    [yvalues addObject:[NSNumber numberWithDouble:22.2]];            [xvalues addObject:[NSNumber numberWithDouble:9.4]];
    [yvalues addObject:[NSNumber numberWithDouble:17.8]];            [xvalues addObject:[NSNumber numberWithDouble:15.3]];
    [yvalues addObject:[NSNumber numberWithDouble:18.3]];            [xvalues addObject:[NSNumber numberWithDouble:9.6]];
    [yvalues addObject:[NSNumber numberWithDouble:28.0]];            [xvalues addObject:[NSNumber numberWithDouble:11.1]];
    [yvalues addObject:[NSNumber numberWithDouble: 8.1]];            [xvalues addObject:[NSNumber numberWithDouble:5.3]];
    [yvalues addObject:[NSNumber numberWithDouble:14.7]];            [xvalues addObject:[NSNumber numberWithDouble:7.8]];
    [yvalues addObject:[NSNumber numberWithDouble:37.8]];            [xvalues addObject:[NSNumber numberWithDouble:25.3]];
    [yvalues addObject:[NSNumber numberWithDouble:15.7]];            [xvalues addObject:[NSNumber numberWithDouble:16.5]];
    [yvalues addObject:[NSNumber numberWithDouble:28.6]];            [xvalues addObject:[NSNumber numberWithDouble:12.6]];
    [yvalues addObject:[NSNumber numberWithDouble:11.7]];            [xvalues addObject:[NSNumber numberWithDouble:12.0 ]];
    [yvalues addObject:[NSNumber numberWithDouble:20.1]];            [xvalues addObject:[NSNumber numberWithDouble:11.5]];
    [yvalues addObject:[NSNumber numberWithDouble:30.1]];            [xvalues addObject:[NSNumber numberWithDouble:17.1]];
    [yvalues addObject:[NSNumber numberWithDouble:18.2]];            [xvalues addObject:[NSNumber numberWithDouble:11.2]];
    [yvalues addObject:[NSNumber numberWithDouble:17.2]];            [xvalues addObject:[NSNumber numberWithDouble:12.2]];
    [yvalues addObject:[NSNumber numberWithDouble:19.6]];            [xvalues addObject:[NSNumber numberWithDouble:10.6]];
    [yvalues addObject:[NSNumber numberWithDouble:29.2]];            [xvalues addObject:[NSNumber numberWithDouble:19.9]];
    [yvalues addObject:[NSNumber numberWithDouble:17.3]];            [xvalues addObject:[NSNumber numberWithDouble:14.5]];
    [yvalues addObject:[NSNumber numberWithDouble:28.2]];            [xvalues addObject:[NSNumber numberWithDouble:15.5]];
    [yvalues addObject:[NSNumber numberWithDouble:38.2]];            [xvalues addObject:[NSNumber numberWithDouble:17.4]];
    [yvalues addObject:[NSNumber numberWithDouble:17.8]];            [xvalues addObject:[NSNumber numberWithDouble:8.4]];
    [yvalues addObject:[NSNumber numberWithDouble:10.4]];            [xvalues addObject:[NSNumber numberWithDouble:10.3]];
    [yvalues addObject:[NSNumber numberWithDouble:19.0]];            [xvalues addObject:[NSNumber numberWithDouble:10.2]];
    [yvalues addObject:[NSNumber numberWithDouble:16.8]];            [xvalues addObject:[NSNumber numberWithDouble:12.5]];
    [yvalues addObject:[NSNumber numberWithDouble:21.5]];            [xvalues addObject:[NSNumber numberWithDouble:16.7]];
    [yvalues addObject:[NSNumber numberWithDouble:15.9]];            [xvalues addObject:[NSNumber numberWithDouble:8.5]];
    [yvalues addObject:[NSNumber numberWithDouble:17.7]];            [xvalues addObject:[NSNumber numberWithDouble:12.2]];

    [test_instance linearRegressionInternal:&slope intercept:&intercept xvalues:xvalues yvalues:yvalues];
    XCTAssert(fabs(slope-1.373)<0.001);
    XCTAssert(fabs(intercept-4.267)<0.001);
}

- (void)testSimpleLinearRegressionCalibration3 {
    // data from https://onlinecourses.science.psu.edu/stat462/node/101 (Example 2)
    SimpleLinearRegressionCalibration* test_instance = [[SimpleLinearRegressionCalibration alloc] init];
    double slope;
    double intercept;
    NSMutableArray* xvalues = [NSMutableArray array];
    NSMutableArray* yvalues = [NSMutableArray array];
    
    [yvalues addObject:[NSNumber numberWithDouble: 1.7080   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7240   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8950   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3360   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9190   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4150   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9420   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6020   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1180   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9320   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4720   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8780   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3520   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4000   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.2560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 0.8390   ]];            [xvalues addObject:[NSNumber numberWithDouble:  4 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5780   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9880   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  3 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3480   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7550   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9800   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1000   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.2820   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0000   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6120   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1750   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7250   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0710   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5470   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7760   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3430   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0760   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6240   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3440   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7320   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0170   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7970   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7030   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6340   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5700   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0160   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4190   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  4 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6980   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5770   ]];            [xvalues addObject:[NSNumber numberWithDouble:  4 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9400   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7470   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5360   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5600   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9620   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7150   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4570   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0900   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7890   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4520   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.8420   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7190   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6950   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7940   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9170   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1440   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.2530   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6590   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5800   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1260   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0290   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9640   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2150   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3880   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1960   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7510   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1650   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6820   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.2920   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6490   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5880   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 0.7960   ]];            [xvalues addObject:[NSNumber numberWithDouble:  4 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5740   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9790   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3540   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7180   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7420   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6030   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6390   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8290   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0840   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3410   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6980   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.1960   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8720   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2190   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8270   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4610   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3380   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0900   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6970   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5620   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0400   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6090   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4290   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6750   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9470   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5720   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3480   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2880   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 0.7910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9050   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4630   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1140   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5270   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0420   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9270   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6650   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3010   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4600   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5920   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7590   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5360   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2590   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0480   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5710   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0460   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7800   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5520   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9530   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7130   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8510   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6240   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8190   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7890   ]];            [xvalues addObject:[NSNumber numberWithDouble:  4 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5030   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9330   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3160   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6060   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.1650   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1020   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2300   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7160   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7900   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.1460   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7170   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7960   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9530   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1190   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6660   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8260   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7090   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8710   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.0920   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2620   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1660   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6900   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1450   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9710   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0950   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6970   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4550   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1640   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1300   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5290   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7260   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4420   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.1020   ]];            [xvalues addObject:[NSNumber numberWithDouble:  4 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8080   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3050   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.0720   ]];            [xvalues addObject:[NSNumber numberWithDouble:  3 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0420   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5120   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.6810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8970   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3700   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3380   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0160   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6390   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3890   ]];            [xvalues addObject:[NSNumber numberWithDouble:  4 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6120   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7960   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0100   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7440   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4850   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4150   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0760   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7280   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8440   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7540   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3430   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3030   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2460   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4760   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2390   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4570   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3820   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6400   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5890   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2260   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8860   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8330   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7150   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9120   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8770   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5390   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8030   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0940   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8550   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9300   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1820   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.3590   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0020   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6990   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5000   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3660   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4180   ]];            [xvalues addObject:[NSNumber numberWithDouble:  4 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3330   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5140   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.7580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5640   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.5910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6240   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7980   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9990   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.0040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  4 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4270   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8260   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6880   ]];            [xvalues addObject:[NSNumber numberWithDouble:  9 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6570   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6720   ]];            [xvalues addObject:[NSNumber numberWithDouble:  6 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0150   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3710   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1150   ]];            [xvalues addObject:[NSNumber numberWithDouble:  5 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3280   ]];            [xvalues addObject:[NSNumber numberWithDouble:  8 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4950   ]];            [xvalues addObject:[NSNumber numberWithDouble:  7 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8840   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3280   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1700   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4700   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5240   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6420   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7410   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.3360   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.8420   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.5500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8410   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1660   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.8160   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5610   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.6540   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6650   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2030   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5490   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2360   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2220   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4900   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1470   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2920   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8890   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2460   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9370   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6460   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9570   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.0070   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3860   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2510   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7620   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.3050   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.9060   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5830   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2360   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4360   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0070   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4890   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8640   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4280   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8190   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.6830   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3520   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1080   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.9940   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.3930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2080   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5920   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6940   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.9570   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3460   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.7890   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5150   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7540   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4630   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6330   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0480   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7450   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3840   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0940   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1830   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0740   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.9770   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3540   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1710   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.8870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6460   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.8450   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9710   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4170   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1750   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9760   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.8350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.0650   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3180   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5960   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3950   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7510   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5420   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6080   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3540   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5990   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.4580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7950   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0600   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5450   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3050   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.7560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7740   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8550   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9880   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4980   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5150   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4250   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4340   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3650   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0860   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6960   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8680   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8130   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.3090   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2550   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4130   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.5930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.1110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.9160   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9750   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9010   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2410   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2250   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 5.2240   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.0730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.0800   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6060   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.4110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0890   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4650   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3430   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2000   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9130   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.8770   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2790   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3470   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8270   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7510   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5380   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0790   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2010   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.8580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2160   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4030   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5010   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5780   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0780   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1860   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 1.6650   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.0810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9740   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2970   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.0730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.4480   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.9840   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2500   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7520   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.6800   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1020   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8620   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6770   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.6810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2550   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.6920   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.5910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0820   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2970   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2160   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2470   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.3240   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3620   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5630   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2060   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5850   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.7200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 5.0830   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4980   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4170   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3640   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3410   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7590   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9530   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0780   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5290   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8660   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0220   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1270   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8660   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6050   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5010   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1230   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7800   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.8470   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7850   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.9240   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1320   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7520   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4490   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4560   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0730   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6880   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3290   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2710   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5300   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9280   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6890   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3320   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9340   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2760   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1100   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8940   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.6370   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8380   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.8310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8120   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7140   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0860   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5190   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2320   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7700   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3410   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0900   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8220   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0380   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5680   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4990   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.1300   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0010   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1320   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5770   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2220   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2800   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6590   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8220   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1400   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2030   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9970   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5620   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0820   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.8060   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3390   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1520   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.4580   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.3910   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1410   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.5790   ]];            [xvalues addObject:[NSNumber numberWithDouble:  12 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.0450   ]];            [xvalues addObject:[NSNumber numberWithDouble:  13 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.7630   ]];            [xvalues addObject:[NSNumber numberWithDouble:  14 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1000   ]];            [xvalues addObject:[NSNumber numberWithDouble:  10 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0690   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7850   ]];            [xvalues addObject:[NSNumber numberWithDouble:  11 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2840   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.5060   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9060   ]];            [xvalues addObject:[NSNumber numberWithDouble:  18 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 5.1020   ]];            [xvalues addObject:[NSNumber numberWithDouble:  19 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5190   ]];            [xvalues addObject:[NSNumber numberWithDouble:  19 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.6880   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.4290   ]];            [xvalues addObject:[NSNumber numberWithDouble:  17 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2790   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.5000   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6350   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6790   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.1980   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3450   ]];            [xvalues addObject:[NSNumber numberWithDouble:  19 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0820   ]];            [xvalues addObject:[NSNumber numberWithDouble:  18 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0820   ]];            [xvalues addObject:[NSNumber numberWithDouble:  17 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9030   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.0040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 5.7930   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.9850   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2200   ]];            [xvalues addObject:[NSNumber numberWithDouble:  18 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.7240   ]];            [xvalues addObject:[NSNumber numberWithDouble:  17 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7310   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.4060   ]];            [xvalues addObject:[NSNumber numberWithDouble:  17 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.5000   ]];            [xvalues addObject:[NSNumber numberWithDouble:  17 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.6740   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 5.6330   ]];            [xvalues addObject:[NSNumber numberWithDouble:  17 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.1220   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.3300   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.6080   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.6450   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7990   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.0860   ]];            [xvalues addObject:[NSNumber numberWithDouble:  18 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8870   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.0700   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.9600   ]];            [xvalues addObject:[NSNumber numberWithDouble:  17 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2990   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.9810   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2640   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.4040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  18 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.2780   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.5040   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 5.6380   ]];            [xvalues addObject:[NSNumber numberWithDouble:  17 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.8720   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 4.2700   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.7270   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.8530   ]];            [xvalues addObject:[NSNumber numberWithDouble:  18 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 2.7950   ]];            [xvalues addObject:[NSNumber numberWithDouble:  16 ]];
    [yvalues addObject:[NSNumber numberWithDouble: 3.2110   ]];            [xvalues addObject:[NSNumber numberWithDouble:  15 ]];
   
    
    [test_instance linearRegressionInternal:&slope intercept:&intercept xvalues:xvalues yvalues:yvalues];
    XCTAssert(fabs(intercept-0.4316)<0.0001);     // ± 0.07790; result from https://www.graphpad.com/quickcalcs/linear2/
    XCTAssert(fabs(slope-0.2220)<0.0001); // ± 0.007518
}

- (void)testPerformanceExample {
    // This is an example of a performance test case.
    [self measureBlock:^{
        // Put the code you want to measure the time of here.
    }];
}

@end
